version: '2.1'
services:
  nginx:
    network_mode: host
    image: nginx:mainline
    restart: always
    mem_limit: 256M
    volumes:
      - ./config:/etc/nginx/conf.d/:ro
      - ./shared:/etc/nginx/shared/:ro
      - ./ssl:/etc/nginx/ssl/:ro
      - /srv/www:/srv/www:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx

